chain=main
server=1
listen=1
listenonion=0
txindex=1

rpcuser=user
rpcpassword=pass
rpcport=28476
rpcallowip=127.0.0.1

port=18465

addnode=seed1.bitcoin-classic.net
addnode=seed1.btc-classic.org
addnode=seed2.bitcoin-classic.net
addnode=seed2.btc-classic.org
addnode=seed3.bitcoin-classic.net
addnode=seed3.btc-classic.org

fallbackfee=0.0001
